#1016 BitbucketStars placeholder implementation.
self-xdsd/self-core pull request #1065
Opened 2021-03-23 10:25 UTC by criske

pr for #1016

2021-03-23 10:25 UTC, zoeself commented
@criske thank you for your Pull Request. I'll assign someone to review it soon.

2021-03-23 10:27 UTC, zoeself commented
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2021-03-26T10:27:17.723398``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

2021-03-25 01:27 UTC, zoeself commented
@amihaiemil Don't forget to close this ticket before the deadline (2021-03-26T10:27:18). You are past the first half of the allowed period.

2021-03-25 07:49 UTC, amihaiemil requested changes
@criske just a comment

2021-03-25 07:49 UTC, amihaiemil commented on self-core-impl/src/main/java/com/selfxdsd/core/BitbucketStars.java
> +        return false;
@criske Pls log it with level ``warning`` and return ``true`` -- if it's not supported, we must assume the operation was successful.

2021-03-25 08:13 UTC, amihaiemil commented
@rultor merge it please

2021-03-25 08:14 UTC, rultor commented
> @rultor merge it please

@amihaiemil OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/24315-806454037)

2021-03-25 08:21 UTC, merged

2021-03-25 08:21 UTC, rultor commented
> @rultor merge it please

@amihaiemil Done! FYI, the full log is [here](https://www.rultor.com/t/24315-806454037) (took me 7min)

2021-03-25 13:27 UTC, zoeself commented
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).