#726: Implement GitlabComment & GitlabIssueComments
self-xdsd/self-core pull request #805
Opened 2020-12-18 02:44 UTC by andreoss

Per #726: 

- Basic implementation for `GitlabComment` & `GitlabIssueComments`

2020-12-18 02:44 UTC, charlesmike commented
@andreoss thank you for your Pull Request. I'll assign someone to review it soon.

2020-12-18 02:46 UTC, charlesmike commented
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2020-12-21T04:46:06.736014``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

2020-12-19 17:56 UTC, amihaiemil requested changes
@andreoss see comments :D

2020-12-19 17:56 UTC, amihaiemil commented on self-core-impl/src/test/java/com/selfxdsd/core/IsComment.java
> + * @since 0.0.41
0.0.44

2020-12-19 17:56 UTC, amihaiemil commented on self-core-impl/src/test/java/com/selfxdsd/core/GitlabIssueCommentsTestCase.java
> + * @since 0.0.41
0.0.44

2020-12-19 17:56 UTC, amihaiemil commented on self-core-impl/src/test/java/com/selfxdsd/core/GitlabCommentTestCase.java
> + * @since 0.0.41
0.0.44

2020-12-19 17:56 UTC, amihaiemil commented on self-core-impl/src/main/java/com/selfxdsd/core/GitlabIssueComments.java
> + * @since 0.0.41
0.0.44

2020-12-19 17:56 UTC, amihaiemil commented on self-core-impl/src/main/java/com/selfxdsd/core/GitlabComment.java
> + * @since 0.0.45
0.0.44

2020-12-19 17:56 UTC, amihaiemil commented on self-core-impl/src/test/java/com/selfxdsd/core/GitlabIssueCommentsTestCase.java
> +public final class GitlabIssueCommentsTestCase {
@andreoss I don't see a test for GilabIssueComments.post(...) and GitlabIssueComments.received(...). Can you write a puzzle for this tests to be added later?

2020-12-19 22:00 UTC, charlesmike commented
@amihaiemil Don't forget to close this ticket before the deadline (2020-12-21T04:46:06). You are past the first half of the allowed period.

2020-12-21 11:51 UTC, charlesmike commented
@amihaiemil Looks like you've missed the task deadline (2020-12-21T04:46:06). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

2020-12-21 11:52 UTC, charlesmike commented
@amihaiemil I couldn't find any assignee for this task. This is either because there are no contributors with role ``REV`` available or because the project does not have enough funds.

Please, make sure there is at least one available contributor with the required role and the project can afford to pay them.

2020-12-22 23:31 UTC, andreoss commented
@amihaiemil Done with your comments.

2020-12-23 10:24 UTC, merged